### Homework 3 Numpy Arrays

1. Open `cars.csv` in jupyter and look at the data. 
2. Notice we have text, integer and float data. 
3. Take care not to overwrite your starter code.

In [1]:
#Starter code. Do NOT modify this cell
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])


1. How can you get help on `np.array`?

Call `dir()` on `np.array`. 

Call `dir()` on `car`.

Note the difference. `car` has methods and attributes we can use.

In [2]:
#help(np.array)
# dir(np.array)
# dir(car)

# When car is instantiated it creates methods and attributes we can use. They are missing in the base class. 

2. What are the numpy datatypes for the `car`,`mpg`, `horsepower` and `origin` arrays? (Hint: Not `type(car)` and use `print()` to print the numpy type.)

In [3]:
print(car.dtype)
print(mpg.dtype)
print(horsepower.dtype)
print(origin.dtype)

object
float64
float64
object


3. `numpy` is often imported as `np`. What is this action called? Why might you do this? 

In [4]:
# This is called aliasing. It can be use to shorted a word and save typing. 
# It can also be used to avoid naming collisions in packages. 

4. Each of the arrays (cars, mpg, cylinders, etc..) has how many dimensions? Show how to find this using code. 

In [5]:
car.ndim

1

5. Show how to:

- multiply the `mpg` array by 12.
- divide the `mpg` array by 3.
- raise the `mpg` array to the power of 4.
- take the square root of the `mpg` array.

In [6]:
mpg * 12
mpg / 3
mpg ** 4
np.sqrt(mpg)

array([4.24264069, 3.87298335, 4.24264069, 4.        , 4.12310563,
       3.87298335, 3.74165739, 3.74165739, 3.74165739, 3.87298335,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       3.87298335, 3.74165739, 0.        , 3.87298335, 3.74165739,
       4.89897949, 4.69041576, 4.24264069, 4.58257569, 5.19615242,
       5.09901951, 5.        , 4.89897949, 5.        , 5.09901951,
       4.58257569, 3.16227766, 3.16227766, 3.31662479, 3.        ,
       5.19615242, 5.29150262, 5.        , 5.        , 0.        ,
       4.35889894, 4.        , 4.12310563, 4.35889894, 4.24264069,
       3.74165739, 3.74165739, 3.74165739, 3.74165739, 3.46410162,
       3.60555128, 3.60555128, 4.24264069, 4.69041576, 4.35889894,
       4.24264069, 4.79583152, 5.29150262, 5.47722558, 5.47722558,
       5.56776436, 5.91607978, 5.19615242, 5.09901951, 4.89897949,
       5.        , 4.79583152, 4.47213595, 4.58257569, 3.60555128,
       3.74165739, 3.87298335, 3.74165739, 4.12310563, 3.31662

6. What is the ___ of `horsepower`?
- sum
- min
- max
- median
- Optional: mode (May need to google help)

In [7]:
np.sum(horsepower)
np.min(horsepower)
np.max(horsepower)
np.median(horsepower)

from scipy import stats
stats.mode(horsepower)


ModeResult(mode=array([150.]), count=array([22]))

7. Select a subset of `acceleration`. 

- Select only the first 5 elements.
- Select every other element (new selection).

In [8]:
acceleration[:5]
acceleration[::2]

array([12. , 11. , 10.5,  9. , 10. , 17.5, 11. , 11. ,  8. ,  9.5, 15. ,
       15.5, 14.5, 17.5, 17.5, 15. , 15. , 18.5, 15.5, 19. , 13. , 15.5,
       15.5, 11.5, 13. , 12. , 13.5, 15. , 14. , 19.5, 19. , 19. , 15.5,
       23.5, 16.5, 12. , 13. , 11. , 13.5, 13.5, 14. , 14. , 18. , 18. ,
       17. , 15. , 13. , 13. , 12.5, 12. , 14.5, 11. , 16.5, 16. , 16. ,
       14. , 13. , 15. , 19.5, 13.5, 14. , 13. , 19.5, 14. , 11. , 13.5,
       16.5, 16. , 19. , 21. , 17. , 16.5, 14.5, 16. , 16.5, 14.5, 19. ,
       15.5, 15. , 16. , 16. , 19.5, 14. , 13.5, 18.5, 19. , 13.5, 16. ,
       16. , 13.5, 17. , 14. , 15. , 14.5, 17.5, 16.9, 17.7, 13. , 13.9,
       15.4, 17.6, 22.2, 14.2, 17.7, 16.2, 12.2, 16.4, 15.7, 21.9, 16.7,
       12. , 14. , 14.8, 15.5, 12.5, 13.7, 16.4, 17.7, 11.1, 12.2, 14.5,
       18.2, 17. , 16.4, 14.5, 13.5, 14.4, 18.6, 15.5, 12.8, 18.2, 15.4,
       17.2, 16.7, 15.1, 13.4, 13.7, 14.2, 14.5, 16.7, 14.9, 13.6, 15.8,
       16.6, 18.2, 18.2, 15.4, 13.2, 14.9, 15. , 14

8. Show how to select the number `99` in the array below. 

In [9]:
select_99 = np.array([[1,2,3],
                      [4,5,99]])

In [10]:
select_99[1,2]

99

9. Select the last element in each subarray (do this with one operation.)

In [11]:
select_more = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
# returns array([3, 6, 9])

In [12]:
select_more[:,2]

array([3, 6, 9])

10. Use the built-in `np.lookfor()` function to search for `'log'`.

Use the function you find and apply it to `mpg`.

In [13]:
# np.lookfor('log')
np.log(mpg)

<ipython-input-13-1603fbcdfe7c>:2: RuntimeWarning: divide by zero encountered in log
  np.log(mpg)


array([2.89037176, 2.7080502 , 2.89037176, 2.77258872, 2.83321334,
       2.7080502 , 2.63905733, 2.63905733, 2.63905733, 2.7080502 ,
             -inf,       -inf,       -inf,       -inf,       -inf,
       2.7080502 , 2.63905733,       -inf, 2.7080502 , 2.63905733,
       3.17805383, 3.09104245, 2.89037176, 3.04452244, 3.29583687,
       3.25809654, 3.21887582, 3.17805383, 3.21887582, 3.25809654,
       3.04452244, 2.30258509, 2.30258509, 2.39789527, 2.19722458,
       3.29583687, 3.33220451, 3.21887582, 3.21887582,       -inf,
       2.94443898, 2.77258872, 2.83321334, 2.94443898, 2.89037176,
       2.63905733, 2.63905733, 2.63905733, 2.63905733, 2.48490665,
       2.56494936, 2.56494936, 2.89037176, 3.09104245, 2.94443898,
       2.89037176, 3.13549422, 3.33220451, 3.40119738, 3.40119738,
       3.4339872 , 3.55534806, 3.29583687, 3.25809654, 3.17805383,
       3.21887582, 3.13549422, 2.99573227, 3.04452244, 2.56494936,
       2.63905733, 2.7080502 , 2.63905733, 2.83321334, 2.39789

11. You your google skills to find the unique items in `origin`. (This may not have been covered in the readings.)

In [14]:
np.unique(origin)

array(['Europe', 'Japan', 'US'], dtype=object)

12. 
- Create a 2D array and print its shape as well as ndim. (Any shape is fine)

- Create a 3D array and print its shape as well as ndim.

- Create a 4D array and print its shape as well as ndim. *It's hard to visualize 4-Dimensions but numpy can do it with ease!*

In [15]:
d2 = np.array([[1,2,3],
              [4,5,6]])
print(d2.ndim)
print(d2.shape)

d3 = np.array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])
print(d3.ndim)
print(d3.shape)

d4 = np.array([[[[1., 1., 1., 1.]]]])
print(d4.ndim)
print(d4.shape)

# TIP: np.ones(1,1,1,1,1,1) to create nDimensional arrays.

2
(2, 3)
3
(3, 3, 3)
4
(1, 1, 1, 4)


13.Use boolean indexing to create an array of `True/False` using `origin` and the value 'US'.

In [16]:
origin=='US'

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True, False, False, False,
       False, False, False,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False, False, False, False,  True, False, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
       False, False,  True,  True, False,  True,  True, False, False,
       False, False,

14. Apply your index (from above) to the `car` array. You should now only see cars that are of US origin. 

In [17]:
car[origin=='US']

array(['Chevrolet Chevelle Malibu', 'Buick Skylark 320',
       'Plymouth Satellite', 'AMC Rebel SST', 'Ford Torino',
       'Ford Galaxie 500', 'Chevrolet Impala', 'Plymouth Fury iii',
       'Pontiac Catalina', 'AMC Ambassador DPL',
       'Chevrolet Chevelle Concours (sw)', 'Ford Torino (sw)',
       'Plymouth Satellite (sw)', 'AMC Rebel SST (sw)',
       'Dodge Challenger SE', "Plymouth 'Cuda 340",
       'Ford Mustang Boss 302', 'Chevrolet Monte Carlo',
       'Buick Estate Wagon (sw)', 'Plymouth Duster', 'AMC Hornet',
       'Ford Maverick', 'AMC Gremlin', 'Ford F250', 'Chevy C20',
       'Dodge D200', 'Hi 1200D', 'Chevrolet Vega 2300', 'Ford Pinto',
       'AMC Gremlin', 'Plymouth Satellite Custom',
       'Chevrolet Chevelle Malibu', 'Ford Torino 500', 'AMC Matador',
       'Chevrolet Impala', 'Pontiac Catalina Brougham',
       'Ford Galaxie 500', 'Plymouth Fury iii', 'Dodge Monaco (sw)',
       'Ford Country Squire (sw)', 'Pontiac Safari (sw)',
       'AMC Hornet Sportabout (

**The remaining questions are OPTIONAL**: The readings did not address all of these so you may have to use some "Google-Fu". 

1.What is an identity matrix? 
Create an identiy matrix of size 5 using an np method. 

In [18]:
np.eye(5)
# a square matrix in which all the elements of the principal diagonal are ones and all other elements are zeros. 
# The effect of multiplying a given matrix by an identity matrix is to leave the given matrix unchanged.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

2. Transpose the following array. 

In [19]:
transpose_me = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
transpose_me.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

3. Why does this multiplication operation fail? 

In [20]:
arr1 = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
arr2 = np.array([[1,2,3],
                      [4,5,6]])

arr1 * arr2

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [21]:
# For matrix multiplication, the number of columns in the first matrix must be equal to the number of rows in the second matrix.

Use numpy to answer the following questions. 

4. What is the average horsepower for `Europe` cars? (Hint: create boolean index of 'US' apply it to horsepower and perform the calculation.)

In [22]:
np.average(horsepower[origin=='Europe'])

78.78082191780823

5. On average are Japanse cars more fuel efficient than US cars? 

In [23]:
print(np.average(mpg[origin=='Japan']))
print(np.average(mpg[origin=='US']))
# Yep

30.450632911392404
19.688188976377955


6. What is the correlation coefficient of `mpg` and `weight`?

In [24]:
np.corrcoef(mpg,weight)

array([[ 1.        , -0.78750994],
       [-0.78750994,  1.        ]])

7. Why might you prefer an `np.array()` over a Python `list`? And when is a Python `list` preferred? 

In [25]:
# np.array() can be faster for complex mathematical operations on large datasets. 
# Python lists are great for everyday tasks!

In [26]:
def collatz(n):
    """ A good example of recursion."""
    
    if n == 1:
        return 
    
    elif n % 2 == 0:
        
        new_n = int(n/2)
        print(new_n)
    
        collatz(new_n)
        
    else:
        new_n = n*3 + 1
        print(new_n)
        
        collatz(new_n)

In [27]:
collatz(55)

166
83
250
125
376
188
94
47
142
71
214
107
322
161
484
242
121
364
182
91
274
137
412
206
103
310
155
466
233
700
350
175
526
263
790
395
1186
593
1780
890
445
1336
668
334
167
502
251
754
377
1132
566
283
850
425
1276
638
319
958
479
1438
719
2158
1079
3238
1619
4858
2429
7288
3644
1822
911
2734
1367
4102
2051
6154
3077
9232
4616
2308
1154
577
1732
866
433
1300
650
325
976
488
244
122
61
184
92
46
23
70
35
106
53
160
80
40
20
10
5
16
8
4
2
1
