# Vectors

In [8]:
import numpy as np
v = np.array([[1],[2],[3]])
v2 = np.array([[-1],[-2],[-3]])
print(v)

[[1]
 [2]
 [3]]


In [3]:
print(v.T)

[[1 2 3]]


In [4]:
v.shape

(3, 1)

# Matrices

In [6]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
M.shape

(3, 3)

In [10]:
#Scalar
x=3.5

#zipping
new_matrix = list(zip(v,v2))
new_matrix

[(array([1]), array([-1])),
 (array([2]), array([-2])),
 (array([3]), array([-3]))]

In [11]:
type(new_matrix)

list

# dot product

We use the dot product to multiply vectors. With 2D vectors, this is the same as matrix multiplication, and we produce a scaler value (a number, not a vector).

Result tells you the degree to which the vectors interact, or the interaction between similar dimensions.

Why do we care? rendering, force diagrams, solar panel tracking

In [12]:
print(v.T)
print(v)

[[1 2 3]]
[[1]
 [2]
 [3]]


In [13]:
# 1*1+ 2*2 + 3*3 
np.dot(v.T,v)

array([[14]])

In [17]:
#directionality example
north = np.array([0,1])
east = np.array([1,0])
south = np.array([0,-1])
west = np.array([-1,0])

#to what degree are the two directions the same
np.dot(north, east)

0

In [18]:
# to what degree are north and south the same?
# create an example
np.dot(north, south)

-1

# Cross product

Type of vector multiplication, but it shows the interaction
between different components of the vector. It tracks all 
the cross interactions between dimensions

when you compute the cross product, you get a new vector
that is perpendicular to both the input vectors

* In each part of the cross product calcualtion, you are leaving out an interaction. * this could be stated better

why do we care? torque and "moment" of a force.
Moment = measure of the tendency to rotate about a particular point

In [19]:
print(v)
print(v2)

[[1]
 [2]
 [3]]
[[-1]
 [-2]
 [-3]]


In [22]:
np.cross(v, v2, axisa = 0,axisb=0)

array([[0, 0, 0]])

# Orthogonality

Two vectors are orthogonal is theyre perpendicular. 
The dot product is 0 or the identity matrix.

$$ A \cdot A^T = I $$

In [24]:
M = np.array([[1,0,0],
            [0,1,0],
            [0,0,1]])
M

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [26]:
# a test for orthogonality is if the matrix and its 
#transpose equal the identity matrix

np.dot(M, M.T)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [27]:
#doesnt produce an identity matrix, and therefor is not orthogonal
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.dot(M,M.T)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [ ]:
# can you find another matrix that is orthogonal?
