In [1]:
import numpy as np
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [6]:
a = np.array([1,2,3,4,5,6])
a.ndim
a.shape

(6,)

In [7]:
a = a.reshape(3,2)
#a = a.reshape(2,-1)
#a = a.ravel()
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
a = a.reshape(2,-1)
#a = a.ravel()
a

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a = a.ravel()
a

array([1, 2, 3, 4, 5, 6])

In [14]:
a = np.arange(10).reshape(5,2) 
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [15]:
a = a.T 
a

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [21]:
a = a.transpose((1,0)) 
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [18]:
a[0,0]  # top-left element

#a[0,-1] # first row, last column
#a[0,:] # first row (many entries)
#a[:,0] # first column (many entries)


0

In [23]:
a[2,0]

4

In [24]:
a[1,:]

array([2, 3])

In [29]:
a = list(range(10)) 
print(a)
#print(a[:3]) # indices 0, 1, 2 
#a[-3:] # indices 7, 8, 9 
print(a[3:8:2]) # indices 3, 5, 7 
#print(a[4:1:-1]) # indices 4, 3, 2 (this one is tricky)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[3, 5, 7]
