In [1]:
import numpy as np  # this imports numpy and renames it as np when used in this notebook

# Questions

### How to derive an integer from an octal number?

https://www.programiz.com/python-programming/methods/built-in/int

In [2]:
# int(value, base)
print(int('3', 8))  # three parts of 8  --  3 == 3
print(int('03', 8))  # zero 8's, three parts of 8  --  0*8 + 3 == 0 + 3
print(int('15', 8))  # have one 8 (1*8), zero parts of 8  --  1*8 + 5 == 8 + 5 == 13
print(int('64', 8))  # have six 8's (6*8), four parts of 8  --  6*8 + 4 == 52 + 4 == 56
print(int('547', 8))  # have five 8*8's (5*8*8)  --  5*8*8 + 4*8 + 7 == 320 + 32 + 7 == 359
print(int('2534', 8))  # have two 8*8*8's (2*8*8*8), five 8*8's (5*8*8), three 8's, four parts of 8  --  2*8*8*8 + 5*8*8 + 3*8 + 4 == 1024 + 320 + 24 + 4 == 1372

3
3
13
52
359
1372


In [3]:
# we talked about RGB color values represented in hexadecimal (6 == hexa, 10 == deci, hence 6+10==16)
# There are 6 values for colors where the first two values represent red, then green (3rd & 4th values), then blue (5th & 6th values)
# having two values for each color, each color then ranges between 0 & 256, representing the amount of that color (red, green, or blue)
# the following are integer values of color values
# normally, RGB colors would only be referred to in the hexademical form, 
# but for the sake of demonstrating the integer conversion to something other than octals, I've printed their integer equivalents
print(int('000000', 16)) # black
print(int('9A00FF', 16)) # bluish purple
print(int('FF00FF', 16)) # purple
print(int('FFFFFF', 16)) # white

0
10092799
16711935
16777215


### Can you discuss in further detail when it's appropriate to use a tuple vs a list?

https://www.simplifiedpython.net/python-tuple-vs-list/

Lists are mutable, tuples are immutable (variable length vs fixed length)

Think of these as making a plan and sticking to it (tuple), or being more flexible to make a change in plans/ad hoc (lists)

Lists are less efficient in size and when operating on them or with them, but lists allow you to be more flexible, especially if you're exploring how to work with your data

In [4]:
a = [1, 2, 3]
print(a)

[1, 2, 3]


In [5]:
tuple(a)

(1, 2, 3)

In [6]:
list(tuple(a))  # you can cast a list as a tuple, do stuff, then cast it back (and vice versa), if you want

[1, 2, 3]

### Please explain how we would use dimensional arrays IRL data science usage.

https://towardsdatascience.com/understanding-high-dimensional-spaces-in-machine-learning-4c5c38930b6a

https://towardsdatascience.com/that-cursing-dimensionality-ac317fb0fdcc

1D - lists, tuples, vectors, array, etc.

Single feature

Response variable

2D - list of lists, matrices, ndarray, dataframe, tabular data, etc.

Feature sets

Single channel image data

Interaction matrices

Covariate matrices

nD - nested lists, tensors, ndarray, multiindex dataframes, etc.

Multichannel image data

Nested grouping of features

2D data in time (series of image snapshots)

Typically, high dimensional spaces can be 'flattened' to a 2D array, such that the shape of that array increases by the number of datapoints, for each dimension flattened

### Broadcasting of numpy array: from the reading:

#### "First off, to make sure that the broadcasting is successful, the dimensions of your arrays need to be compatible. 

#### Two dimensions are compatible when the are equal. Consider the following example: 

#### 'x has dimension of 3x4 and y has a dimension of 4.'"

### Does that mean they are compatible? 

### Even if x is a 2D array and y is a 1D array, are they still compatible, since the column numbers match?'"


https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

The phrasing is mixing the use of the term dimension

3x4 is the shape of a 2D array, 3 rows & 4 columns, shape is (3, 4)

x has shape of a 3x4 array and y has a length of 4 (and shape = (4,)). aka, x is 2D and y is 1D

The length of the shape tuple (also known as the rank of the array) is the dimension of the array

General broadcasting rules require 1. that both arguments have equal dimension or 2. one of the arguments is 1D with matching shape to the axis of interest of the other argument

In [7]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [8]:
x.size

6

In [9]:
np.shape(x)

(2, 3)

In [10]:
x.ndim

2

In [11]:
len(np.shape(x))

2

In [12]:
x + [10, 20, 30]  # broadcasts the right array to each row of x

array([[11, 22, 33],
       [14, 25, 36]])

In [13]:
x + [100, 200]  # doesn't work, bc right array doesn't match the column shape of x (3)

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [14]:
x + [[100], [200]]  # this works, bc the right array has shape (2,1), not (2,) (notice in the error message above the shape comment)

array([[101, 102, 103],
       [204, 205, 206]])

In [15]:
np.shape([[100], [200]])

(2, 1)

In [16]:
np.shape([100, 200])

(2,)

### In the floor, ceil, and rint homework, required a line in the coding program to include a print option line for spacing. 

### numpy.set_printoptions(sign=' ') in order to get the correct answer. 

### However in the arrays question, it had the same spacing requirement for output, but I didn't need to include the print option line. 

### What determines when you need to add this line of code?

If these are in the same code block, then you'd only need to call this once. If instead each function is separated, then you would call the print options each time.

In [17]:
np.set_printoptions(sign=' ')

In [18]:
def spacing(list_like_object):
    print('now in spacing')
    b = [str(x) for x in list_like_object]  # list comprehension to type cast each element as a string
    print(b)
    c = np.floor(a)  # floor all elemnts in the list-like object, a
    print(c)
    d = ' ' + ' '.join([str(x) for x in c])  # add the beginning space
    print('done with spacing')
    return d

In [19]:
a = [1.2, 2.5, 3.0]  # a list
print(a)
result = spacing(a)
print(result)

[1.2, 2.5, 3.0]
now in spacing
['1.2', '2.5', '3.0']
[ 1.  2.  3.]
done with spacing
 1.0 2.0 3.0


### Can we specify dtype as integer for any numpy function? 

### For instance, np.zeros((1,2), dtype=np.int) works, but np.divide((x,y), dtype=np.int) does not work. 

### What am I supposed to do if I want to return an integer after division?


Yes, you can specify dtype

https://docs.scipy.org/doc/numpy/reference/generated/numpy.divide.html

I think this is primarily just a typo with using (x,y), giving divide a tuple, not two values as expected.

In [20]:
# uncomment the following line and run it to see the documentation about numpy's divide function
#np.divide?

# note the Call signature, it specifies how to call the function and that it expects args & kwargs
# note the Type, it indicates ufunc, which is a special, under-the-hood/behind-the-scenes numpy data type that may help google questions about the function
# note the String form, it states that the ufunc name is true_divide, 
#   which is different from integer or floor division in that it returns real valued floats, not ints
# note the Docstring, it shows the function definition with all parameters that it expects & can handle, ie each arg & kwarg specified. 
#   The / indicates the end of args and beginning of kwargs. 
#   np.divide apparently is equivalent to np.true_divide, taking two args: x1 & x2
#   and a bunch of kwargs: out, where, casting, order, dtype, etc.
# note the Parameters, each arg and kwarg are explained in greater detail, including their expected dtypes & some description

In [21]:
some_array = [[14.5, 5], [3, 2]]
print(some_array)

[[14.5, 5], [3, 2]]


In [22]:
np.divide((some_array), dtype=np.int)  # this is the code from the question that doesn't work, again, it's bc a tuple is given, not two args

ValueError: invalid number of arguments

In [23]:
np.divide(some_array[0], some_array[1])  # divide [14, 5] by [3, 2], that is [14/3, 5/2]

array([ 4.83333333,  2.5       ])

In [24]:
np.floor_divide(some_array[0], some_array[1])

array([ 4.,  2.])

In [25]:
x = np.divide(some_array[0], some_array[1])
np.rint(x)

array([ 5.,  2.])

In [26]:
x = np.divide(some_array[0], some_array[1])
np.ceil(x)

array([ 5.,  3.])

In [27]:
x = np.divide(some_array[0], some_array[1])
np.floor(x)

array([ 4.,  2.])

In [28]:
x = np.divide(np.rint(some_array[0]), np.rint(some_array[1]))  # this doesn't print int values, bc rounding ocurrs before division
print(x)

[ 4.66666667  2.5       ]


In [29]:
x = np.divide(some_array[0], some_array[1])  # this prints int values, bc round ocurrs after division
print(np.rint(x))

[ 5.  2.]


### How can we append to rows? 

### I have an array: 

#### my_2d_array = [[1 2 3 4], [5 6 7 8]] 

### and I was able to append to columns using 

#### np.append(my_2d_array, [[7], [8]], axis=1) 

### but the following did not work: 

#### new_2d_array = np.append(my_2d_array, [[7], [8], [1], [1]], axis=0)

Looks like you're trying to append a list of lists, not a list of ints

https://docs.scipy.org/doc/numpy/reference/generated/numpy.append.html

For the second arg: "must be of the correct shape (the same shape as arr, excluding axis)."

Another incorrect attempt is np.append(my_2d_array, [7 8 1 1], axis=1), 

bc shape of second arg is (4,), not (2, 4)

Without axis, append flattens the arrays to 1D

In [30]:
my_2d_array = [[1, 2, 3, 4], [5, 6, 7, 8]]  # what was given
print(my_2d_array)

[[1, 2, 3, 4], [5, 6, 7, 8]]


In [31]:
np.append(my_2d_array, [[7], [8]], axis=1)  # working append to columns

array([[1, 2, 3, 4, 7],
       [5, 6, 7, 8, 8]])

In [32]:
np.append(my_2d_array, [[7], [8], [1], [1]], axis=0)  # does not work due to appending list of lists, not list of ints
# note the last line of the error message describing the shape along each dimension

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 1

In [33]:
np.append(my_2d_array, [[7, 8, 1, 1]], axis=0)  # this works, bc this appends a list of ints, matching shape with my_2d_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [7, 8, 1, 1]])

### I can use numpy for HackerRank exercises, but I have a harder time writing the code to take input. 

### For instance, in the exercise for vector math, I saw people use the following code:

### B = (np.array([input().split(' ') for _ in range(N)], dtype=int)). How does it exactly work and why did we not use dimension M in this code?

Honestly, while this may work, it is not easily readable (I find it a working, but poor solution), since it does numerous things in one line.

Although it can be difficult, you should aim to write easily readable code, where each line does one (maybe two things at worst).

Think of writing code as you would to write a story. 

If anyone can, without your prompts or help, read it and understand without much effort what you're trying to do, then you've got great code, a great story.

Back to the question:

I'm not sure what M is, so I'll ignore that.

Let's break down this one-liner:

    Range(N) gives an iterable range between [0, N)
    The _ is used as a dummy variable
    input() calls function input and returns its value at return line (a str)
    Being a str from input(), split is called to separate that str by ' '
    input().split(' ') is then a list of str values from input
    The list comprehension of [input().split(' ') for _ in range(N)] then calls input().split(' ') N times, building a list of lists (2D)
    With the list comprehension part as the arg to np.array, this generates a 2D array containing N rows of input, such that the elements are int (dtype=int)
    This 2D array is then put in as the first and only element of an array (…) and assigned to B

Alternatively, a better story would be:

    input_str = input()
    input_list = input_str.split(' ')
    input_N_list = [input_list for _ in range(N)]
    input_array = np.array(input_n_list, dtype=int)
    B = (input_array)

In [34]:
N = 4  # let's assume N has some value, in this case 4
input_return_value = '0 1 2 3'  # let's assume input() read a file or something, then returned a string. 
# I'm using context clues, how input() is used to infer what data type it is. I see split(' ') called from it, so it looks like a string.

In [35]:
B = (np.array([input_return_value.split(' ') for _ in range(N)], dtype=int))
print(B)

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


In [36]:
# my alternate story, pardon that it lacks exciting action & spice
# at least it gets the job done, and hopefully is easier to understand (the goal for readable code)
input_list = input_return_value.split(' ')
input_n_list = [input_list for _ in range(N)]
input_array = np.array(input_n_list, dtype=int)
B = (input_array)
print(B)

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


### Why does print(max('gold', 'tin')) return 'tin?

https://www.geeksforgeeks.org/max-min-python/

Max returns the lexicographically 'larger' str, ie str found at the end of lexocographic sorting
    
Upper case before lower case
    
Punctuation, number, upper case, lower case
    
https://www.programiz.com/python-programming/examples/alphabetical-order
   
max('Argentina', 'Brazil', 'America', 'Egypt', 'Lesotho', 'India', 'Mongolia') returns …?

In [37]:
max('Argentina', 'Lesotho', 'Mongolia')

'Mongolia'

In [38]:
max('Argentina', 'Lesotho', 'Mongolia', 'Mongol')

'Mongolia'

In [39]:
max('Argentina', 'Lesotho', 'Mongolia', 'Mongol', 'continent')

'continent'

### Why is it that when squared is called, there is nothing to return? 

### When squared is performed it returns a value? 

### Is the code wrong or are there some rules that I do not know?

def squared(x):

    result = x*2   # * does multiplication, ** does power
    return (result)

#### print(squared(5)) -> 10

#### print(squared) -> <function squared at 0x…>

#### y = squared

#### print(y) -> <function squared at 0x…>

#### list(map(squared, [1, 2, 3, 4, 5])) -> [2, 4, 6, 8, 10]

https://stackoverflow.com/questions/37310706/difference-between-matlab-function-handle-and-python-function-object

Calling the function without parens '()' calls the handle, a reference to the function (the address of the function in the computer memory).

Calling the function with parens, executes the function given whatever input parameters.

The code is fine, maybe you're observing some new behaviors

map applies a function (squared) to some arguments ([1, 2, 3, 4, 5])

list(map…) converts the map type to a list, hence the output

map on its own would return <map object at 0x…>

In [40]:
def squared(x):
    result = x*2   # note that * does multiplication, ** does power, we'll work with the code as given
    return (result)

In [41]:
print(squared(5)) # 10

10


In [42]:
print(squared) # the function handle

<function squared at 0x110faf158>


In [43]:
y = squared
print(y) # assigning the handle to another variable, y. Note the same 0x... value is the same, we've assigned the function address, nothing more

<function squared at 0x110faf158>


In [44]:
list(map(squared, [1, 2, 3, 4, 5]))

[2, 4, 6, 8, 10]

In [45]:
map(squared, [1, 2, 3, 4, 5])  # some functions return special types

In [46]:
range(4)  # another function that returns a weird type, in this case, range is a type of iterable that can be used in things like for loops

range(0, 4)